### ISSUE TITLE
Use Extracted Krab Repository

### ISSUE THREAD

**Issue by bonedaddy** [RTradeLtd/rtfs#24]
# Assignee: unassigned

`krab` has been extracted into a separate repository. We should remove `krab` that is bundled within this repository, and instead for tools like `keystore.go` leverage the extracted `krab` repository.

Relates to [kaas/#9](https://github.com/RTradeLtd/kaas/issues/9)

Work required for this ticket:
* Update dependencies, and change imports to use extracted krab repository
* Remove `krab` that is bundled within the repository

**Comment by arku** [comment]
@postables Let me take a stab at this one.
